Add help.

diff --git a/ticket b/ticket
--- a/ticket
+++ b/ticket
@@ -5,11 +5,51 @@
 ## in a plain text file in git root directery       ##
 ######################################################
 
+## Configuration
+# TODO export it to a separate ticket_setting.conf file
+# in git repository top level
 directory="tickets/"
 labels=("bug" "enhancement" "documentation")
 
 
-## Exit if we are not in git repository
+function print_help { 
+    echo "Usage:"
+    echo "  ticket -h                   Display this help message."
+    echo "  ticket                      Add a new ticket."
+    echo "  ticket add                  Also add a new ticket."
+    echo "  ticket close <ticket_id>    Set <ticket_id> as closed."
+    echo "  ticket edit <ticket_id>     Open <ticket_id> in text editor."
+    echo "  ticket list                 List all tickets."
+    echo "  ticket list -o              List all open tickets."
+    echo "  ticket list -c              List all closed tickets."
+    echo "  ticket list -l <label>      List all tickets with label <label>."
+    echo "  ticket list -a <author>     List all tickets with author <author>."
+    echo "  All commands must be called in a git repository."
+    exit 0
+}
+
+
+function print_invalid_option {
+    echo "Invalid option: -$1" 1>&2
+    exit 1
+}
+
+
+## We allow to show help from anywhere
+while getopts ":h" opt
+do
+    case ${opt} in
+        h)
+            print_help
+            ;;
+        \?)
+            print_invalid_option $OPTARG
+            ;;
+    esac
+done
+shift $((OPTIND -1))
+
+## For rest of script, exit if we are not in git repository
 repository=$(git rev-parse --is-inside-work-tree 2> /dev/null)
 if [ "$repository" != "true" ]
 then
@@ -17,7 +57,6 @@ then
 	echo "Exit"
 	exit 1
 fi
-	
 ## Search git top level directory, cd to it.
 cd "$(git rev-parse --show-toplevel)"
 
